apiVersion: 1

datasources:
  - name: ClickHouse - Ralph
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    basicAuth: false
    jsonData:
      server: clickhouse
      port: 8123
      protocol: http
      username: ${CLICKHOUSE_USER}
      defaultDatabase: ${CLICKHOUSE_DB}
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
    isDefault: true
    editable: true